# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs: 
  Install:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 
      - run: 
          name : Install npm
          command: | 
            cd ./js-package
            npm run test
            npm install
      - save_cache:
          paths: [js-package/node_modules]
          key: node_modules
  Lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name : install hado Lint 
          command: | 
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
  
      - run:
          name : Hadolint 
          command: |
            hadolint Dockerfile --ignore DL3008 --ignore DL3016
           
  

  DeployInfra-VPC:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: VPC Deploy
          command: |   
            pwd    
            aws cloudformation create-stack --stack-name vpc-capstone \
              --template-body file://./AWS-cloudformation/Network.yml \
              --parameters file://./AWS-cloudformation/Network-Prameters \
                | grep -i StackId >> file.stdout \
                 
          
          
               
workflows:
  default:
    jobs:
      - Install
      - Lint:
          requires: [Install]
      - DeployInfra-VPC:
          requires: [Lint]    
      
                
            

            
            
