- name: "Configuration Play"
  hosts: web
  user: ubuntu
  gather_facts: false


  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
   - name: Install Docker
     become: true
     apt: name=docker.io state=present force_apt_get=yes
   
   - name: "Copy files to EC2 instance"
     copy:
        src: /root/project
        dest: /home/ubuntu
        force : yes 

    