- name: "Configuration Play"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: true


  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
  - name: "Copy files to EC2 instance"
    copy:
      src: /root/project
      dest: /home/ubuntu
      force : yes

  - name: "APT: Install aptitude package"
    apt:
      name: aptitude
      force_apt_get: yes

  - name: upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes

  - name : install counter track
    apt:
     name: conntrack

  - name: enable docker service
    command: sudo systemctl enable docker.service
  
  - name: make minikube.sh executable
    command: sudo chmod +x /home/ubuntu/project/Ansible/minikube.sh

  - name: make kubectl.sh executable
    command: sudo chmod +x /home/ubuntu/project/Ansible/kubectl.sh   

  - name: Install kubectl
    shell: bash /home/ubuntu/project/Ansible/kubectl.sh

  - name: Make the kubectl binary executable
    command: sudo chmod +x ./kubectl

  - name: sudo mv ./kubectl /usr/local/bin/kubectl
    command: sudo mv ./kubectl /usr/local/bin/kubectl



  - name: Install minikube
    script:
     cmd: minikube.sh
     chdir: /home/ubuntu/project/Ansible


  - name : Start minbikube
    command: sudo -i
    command: minikube start --driver=none

  - name: Create POD
    command : sudo kubectl apply -f /home/ubuntu/project/kube/client-pod.yaml

  - name: Create Seervice 
    command : /home/ubuntu/project/kube/client-node-yaml      
