- name: "Configuration Play" 
  hosts: web
  user: ubntu
  gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
    - name: "Copy files to EC2 instance"
      copy:
        src: /root/project
        dest: /home/ubuntu
        force : yes
    
    - name:
      make:
        chdir: /home/ubuntu/project
        target: build


    - name:
      make:
        chdir: /home/ubuntu/project
        target: run
      become: yes   





        
    



    