- name: "Configuration Play"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: true


  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
  - name: "Copy files to EC2 instance"
    copy:
      src: /root/project
      dest: /home/ubuntu
      force : yes
  
  - name: "APT: Install aptitude package"
    apt:
      name: aptitude
      force_apt_get: yes
  
  - name: upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes   
  
  - name: enable docker service
    command: sudo systemctl enable docker.service

  - name: Install kubectl 
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubectl
  - name: Install kubectl 
    shell: sudo bash /home/ubuntu/Ansible/minikube.sh
  - name : Start minbikube
    command: minikube start --driver=none    







  



