- name: "Configuration Play"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes


  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:


  - name: "Copy files to EC2 instance"
    copy:
      src: /root/archive.tar.gz
      dest: /home/
      force : yes

  - name:  Unarchive
    unarchive:
     src: /home/archive.tar.gz
     dest: /home/ubuntu
     remote_src: yes

  - name: "APT: Install aptitude package"
    apt:
      name: aptitude
      force_apt_get: yes

  - name: upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes

  - name : install counter track
    apt:
     name: conntrack

  - name: enable docker service
    command: sudo systemctl enable docker.service

  - name: make minikube.sh executable
    file: dest=/home/ubuntu/project/Ansible/minikube.sh mode=a+x

  - name: make kubectl.sh executable
    file: dest=/home/ubuntu/project/Ansible/kubectl.sh mode=a+x



  - name: Install kubectl
    script:
     cmd: kubectl.sh
     chdir: /home/ubuntu/project/Ansible/

  - name: Make the kubectl binary executable
    file: dest=/home/ubuntu/project/Ansible/kubectl mode=a+x

  - name: mv /home/ubuntu/project/Ansible/kubectl /usr/local/bin/kubectl
    stat: path=/home/ubuntu/project/Ansible/kubectl 
    register: kubectl
  - name:
    command: mv /home/ubuntu/project/Ansible/kubectl /usr/local/bin/kubectl
    when: kubectl.stat.exists

  - name: Install minikube
    script:
     cmd: minikube.sh
     chdir: /home/ubuntu/project/Ansible
 
  - name: chmod +x minikube
    file: dest=/home/ubuntu/project/Ansible/minikube  mode=a+x
  
  - name:  mv /home/ubuntu/project/Ansible/minikube /usr/local/bin/
    stat: path=/home/ubuntu/project/Ansible/minikube
    register: minikube
  - name: 
    command: mv /home/ubuntu/project/Ansible/minikube /usr/local/bin/ 
    when: minikube.stat.exist
  
  - name: chmod +x /home/ubuntu/project/start-minikube.sh
    command: dest=/home/ubuntu/project/start-minikube.sh mode=a+x

  - name: Start minbikube
    make:
     target: start
     chdir: /home/ubuntu/project/




  - name: make service
    command: kubectl apply -f /home/ubuntu/project/kube/client-node-port.yaml
    become: true

  - name: make pod
    command: kubectl apply -f /home/ubuntu/project/kube/client-pod.yaml
    become: true
