- name: "Configuration Play" 
  hosts: web
  user: ec2-user
  gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
    - name: "Copy files to EC2 instance"
      copy:
        src: /root/project/*
        dest: /home/ec2-user

    